version: "3.8"
services:
  db:
    container_name: hello-postgres
    image: postgres:15.2
    volumes:
      - db_data:/var/lib/postgresql/data:cached
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db_net
  app:
    container_name: hello-elixir
    depends_on:
      - db
    build: .
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "4000:4000"
    restart: always
    tty: true
    networks:
      - db_net

networks:
  db_net:
    driver: bridge

volumes:
  db_data: {}
